app:
  lnh:
    db:
      url: jdbc:mysql://localhost:3306/lnh_sku_db
      username: root
      password: root
      dialect: org.hibernate.dialect.MySQL8Dialect
      driver-class-name: com.mysql.cj.jdbc.Driver