spring:
  application:
    name: lnh_sku_management_service
  datasource:
    url: ${app.lnh.db.url}
    username: ${app.lnh.db.username}
    password: ${app.lnh.db.password}
    driver-class-name: ${app.lnh.db.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: ${app.lnh.db.dialect}
        format_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
